"""Split a multi-chapter script draft into one markdown file per chapter.

    python scripts/split_script.py [references/sources/SCRIPT_DRAFT_AUG_23.md]

A chapter starts at the first bold line that begins with "Chapter <n>" (as a word or a
digit, e.g. "**Chapter Two: …**", "**CHAPTER 3**", "**Chapter Six Lead Question**");
chapter 1 also takes everything before chapter 2 (the draft's preamble). Writes
references/<SOURCE NAME>_CHAPTER_<n>.md. The source stays in references/sources/,
which agents don't read. Each chapter file is marked as an idea draft
(<!-- reference: draft -->), so agents mine it for ideas instead of treating it as canon.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
V00 = ROOT / "campaigns" / "prosperity" / "novel" / "drafts" / "v00"
SOURCE = V00 / "_rough" / "SCRIPT_DRAFT_AUG_23.md"
OUT = V00 / "script"
WORDS = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6,
         "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11, "twelve": 12}
START = re.compile(r"^\*\*\s*chapter\s+(\d+|" + "|".join(WORDS) + r")\b", re.I)


def number(token):
    return int(token) if token.isdigit() else WORDS[token.lower()]


def main(source):
    lines = source.read_text().split("\n")
    starts = {}
    for i, line in enumerate(lines):
        m = START.match(line.strip())
        if m:
            starts.setdefault(number(m.group(1)), i)
    starts[min(starts)] = 0 if starts else 0
    order = sorted(starts.items(), key=lambda kv: kv[1])
    for k, (n, start) in enumerate(order):
        end = order[k + 1][1] if k + 1 < len(order) else len(lines)
        body = "\n".join(lines[start:end]).strip()
        out = OUT / f"{source.stem}_CHAPTER_{n}.md"
        out.write_text(f"<!-- reference: draft — chapter {n} of {source.name}, generated by "
                       f"scripts/split_script.py; edit the source and rerun -->\n\n"
                       f"> **Idea draft, not the script.** This was put together to get the ideas for "
                       f"chapter {n} on paper. Use it for beats, intent and moments worth keeping; "
                       f"the room writes the real script.\n\n{body}\n")
        print(f"references/{out.name}: lines {start + 1}-{end}, {len(body) // 1000} KB")


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else SOURCE)
